<a href="https://colab.research.google.com/github/jaison-1920/pytorch_practice/blob/main/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello world")

hello world


In [2]:
print("pytorch practice")

pytorch practice


In [3]:
import numpy as np
import torch


Tensors:
* Multidimensional arrays: Similar to NumPy arrays, tensors are multidimensional arrays used for numerical computations.
* Built on NumPy
* Hardware acceleration: Tensors can leverage hardware acceleration from GPUs for faster computations in deep learning models.

In [4]:
np_1 = np.arange(10)
np_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np_1 = np_1.reshape(2,-1)
np_1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
np_1.dtype

dtype('int64')

In [7]:
np_1[0][1] = 22
np_1

array([[ 0, 22,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [8]:
tensor = torch.rand(10)
tensor

tensor([0.0311, 0.8223, 0.4253, 0.5622, 0.4792, 0.2519, 0.8482, 0.0391, 0.8013,
        0.0994])

In [9]:
tensor = tensor.reshape(5,-1)
tensor

tensor([[0.0311, 0.8223],
        [0.4253, 0.5622],
        [0.4792, 0.2519],
        [0.8482, 0.0391],
        [0.8013, 0.0994]])

In [10]:
tensor.dtype

torch.float32

In [11]:
tensor[0][1] = 2
tensor

tensor([[0.0311, 2.0000],
        [0.4253, 0.5622],
        [0.4792, 0.2519],
        [0.8482, 0.0391],
        [0.8013, 0.0994]])

In [12]:
tensor_1 = torch.rand(10)
tensor_1

tensor([0.4995, 0.5645, 0.3515, 0.6037, 0.0067, 0.3068, 0.6684, 0.1391, 0.8598,
        0.8516])

In [13]:
tensor_1[1]=2
tensor_1

tensor([0.4995, 2.0000, 0.3515, 0.6037, 0.0067, 0.3068, 0.6684, 0.1391, 0.8598,
        0.8516])