<a href="https://colab.research.google.com/github/jaison-1920/pytorch_practice/blob/main/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
print("hello world")

hello world


In [66]:
print("pytorch practice")

pytorch practice


In [67]:
import numpy as np
import torch


Tensors:
* Multidimensional arrays: Similar to NumPy arrays, tensors are multidimensional arrays used for numerical computations.
* Built on NumPy
* Hardware acceleration: Tensors can leverage hardware acceleration from GPUs for faster computations in deep learning models.

In [68]:
np_1 = np.arange(10)
np_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np_1 = np_1.reshape(2,-1)
np_1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
np_1.dtype

dtype('int64')

In [71]:
np_1[0][1] = 22
np_1

array([[ 0, 22,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [72]:
tensor = torch.rand(10)
tensor

tensor([0.4076, 0.7695, 0.5315, 0.6530, 0.2050, 0.1605, 0.5697, 0.9402, 0.2600,
        0.7440])

In [73]:
tensor = tensor.reshape(5,-1)
tensor

tensor([[0.4076, 0.7695],
        [0.5315, 0.6530],
        [0.2050, 0.1605],
        [0.5697, 0.9402],
        [0.2600, 0.7440]])

In [74]:
tensor.dtype

torch.float32

In [75]:
tensor[0][1] = 2
tensor

tensor([[0.4076, 2.0000],
        [0.5315, 0.6530],
        [0.2050, 0.1605],
        [0.5697, 0.9402],
        [0.2600, 0.7440]])

In [76]:
tensor_1 = torch.rand(10)
tensor_1

tensor([0.0526, 0.2979, 0.9131, 0.7385, 0.4391, 0.1341, 0.5907, 0.7973, 0.6357,
        0.6514])

In [77]:
tensor_1[1]=2
tensor_1

tensor([0.0526, 2.0000, 0.9131, 0.7385, 0.4391, 0.1341, 0.5907, 0.7973, 0.6357,
        0.6514])

Maths in tensors
* addition, subtraction, multiplication, division
* remainder,exponent
* Reassignment



In [78]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor((5,6,7,8))

In [79]:
# Addition
print(tensor_a + tensor_b)
print(torch.add(tensor_a,tensor_b))
print(tensor_a.add(tensor_b))

tensor([ 6,  8, 10, 12])
tensor([ 6,  8, 10, 12])
tensor([ 6,  8, 10, 12])


In [80]:
# Subtraction
print(tensor_b - tensor_a)
print(torch.sub(tensor_b,tensor_a))
print(tensor_b.sub(tensor_a))

tensor([4, 4, 4, 4])
tensor([4, 4, 4, 4])
tensor([4, 4, 4, 4])


In [81]:
# multiplication
print(tensor_a*tensor_b)
print(torch.mul(tensor_a,tensor_b))
print(torch.multiply(tensor_a,tensor_b))
print(tensor_a.mul(tensor_b))

tensor([ 5, 12, 21, 32])
tensor([ 5, 12, 21, 32])
tensor([ 5, 12, 21, 32])
tensor([ 5, 12, 21, 32])


In [82]:
#Division
print(tensor_b/tensor_a)
print(torch.div(tensor_b,tensor_a))
print(tensor_b.div(tensor_a))

tensor([5.0000, 3.0000, 2.3333, 2.0000])
tensor([5.0000, 3.0000, 2.3333, 2.0000])
tensor([5.0000, 3.0000, 2.3333, 2.0000])


In [83]:
#remainder
print(tensor_b%tensor_a)
print(torch.remainder(tensor_b,tensor_a))
print(tensor_b.remainder(tensor_a))

tensor([0, 0, 1, 0])
tensor([0, 0, 1, 0])
tensor([0, 0, 1, 0])


In [84]:
#Exponents / power
print(torch.pow(tensor_a,tensor_b))
print(tensor_a.pow(tensor_b))

tensor([    1,    64,  2187, 65536])
tensor([    1,    64,  2187, 65536])


In [85]:
# reassignment
tensor_a = tensor_a+tensor_b
print(tensor_a)

tensor([ 6,  8, 10, 12])


In [86]:
# Reassignment using add_ function
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor((5,6,7,8))
tensor_a.add_(tensor_b)
print(tensor_a)

tensor([ 6,  8, 10, 12])
